
Components.utils.import("resource://gre/modules/XPCOMUtils.jsm");var loader=Components.classes["@mozilla.org/moz/jssubscript-loader;1"].getService(Components.interfaces.mozIJSSubScriptLoader);loader.loadSubScript("chrome://ytoolbar/content/utils.js");loader.loadSubScript("chrome://ytoolbar/content/trackinginterfaces.js");loader.loadSubScript("chrome://ytoolbar/content/logger.js");const MAX_ERROR_PAGE_SIZE=512;function Yahoo404Converter(){var _self=this;var _configMgr=Components.classes["@yahoo.com/configmanager;1"].getService(Components.interfaces.nsIYahooConfigManager);var _urlBarXULId="urlbar";var _errorsToTrap=[];var _blackList=[];this.navAssistBaseUrl=null;this.enabled=false;this.observe=function(aSubject,aTopic,aData){try{if(aTopic=="nsPref:changed"){yahooUtils.setTimeout(function(){if(_configMgr.getBoolValue("general.navassist")){Components.classes['@mozilla.org/observer-service;1'].getService(Components.interfaces.nsIObserverService).addObserver(_self,"http-on-examine-response",false);_self.enabled=true;}
else{Components.classes['@mozilla.org/observer-service;1'].getService(Components.interfaces.nsIObserverService).removeObserver(_self,"http-on-examine-response");_self.enabled=false;}},5);}
if(aTopic=="yahoo-feed-updated"){yahooUtils.setTimeout(function(){var yahooLocalStorage=Components.classes["@yahoo.com/localstorage;1"].getService(Components.interfaces.nsIYahooLocalStorage);var navAssistParams=yahooLocalStorage.getObject("yahoo-toolbar-epa.yhash");if(navAssistParams){navAssistParams=navAssistParams.wrappedJSObject.object;var errs=navAssistParams.errs.split("|");_errorsToTrap.splice(0,_errorsToTrap.length);errs.forEach(function(err){_errorsToTrap.push(parseInt(err));},_self);var epablist=navAssistParams.epablist.split("|");_blackList.splice(0,_blackList.length);epablist.forEach(function(url){_blackList.push(url);},_self);var intl=_configMgr.getCharValue("installer.language");if(!intl)intl='us';_self.navAssistBaseUrl=navAssistParams.server;_self.navAssistBaseUrl=_self.navAssistBaseUrl.replace(/\\\\u0001/g,"\x01");_self.navAssistBaseUrl=_self.navAssistBaseUrl.replace("__Domain_Prefix__",intl);var scVal=_configMgr.getCharValue("toolbar.frc");if(scVal==null||scVal==""){scVal=_configMgr.getCharValue("toolbar.sc")}
_self.navAssistBaseUrl=_self.navAssistBaseUrl.replace(/\x01\$REG_sc\x01/,scVal);_self.navAssistBaseUrl=_self.navAssistBaseUrl.replace(/\x01\$REG_tc\x01/,_configMgr.getCharValue("toolbar.tc"));_self.navAssistBaseUrl=_self.navAssistBaseUrl+"&.intl="+intl+"&.cv="+_configMgr.getCharValue("installer.version");_self.navAssistBaseUrl=unescape(_self.navAssistBaseUrl);_urlBarXULId=navAssistParams.xulid?navAssistParams.xulid:_urlBarXULId;_self.enabled=_configMgr.getBoolValue("general.navassist")?true:false;}else{_self.enabled=false;}},5);}
if(aTopic=="http-on-examine-response"){aSubject.QueryInterface(Components.interfaces.nsIHttpChannel);if(aSubject.notificationCallbacks&&_self.enabled){var url=aSubject.URI.spec;var win=aSubject.notificationCallbacks.QueryInterface(Components.interfaces.nsIInterfaceRequestor).getInterface(Components.interfaces.nsIDOMWindow);var winMediator=Components.classes['@mozilla.org/appshell/window-mediator;1'].getService(Components.interfaces.nsIWindowMediator);var topWin=winMediator.getMostRecentWindow("navigator:browser");var urlAddrBar=topWin.document.getElementById(_urlBarXULId).value;urlNoSchema=url.substr(url.indexOf("://")+3);urlAddrBar=urlAddrBar.indexOf("://")>0?urlAddrBar.substr(urlAddrBar.indexOf("://")+3):urlAddrBar;if(urlAddrBar.indexOf(urlNoSchema)>=0){var response=aSubject.responseStatus;var responseLength=aSubject.contentLength;for(var j in _blackList){if(url.match(_blackList[j])){return;}}
for(var i=0;i<_errorsToTrap.length;i++){if(_errorsToTrap[i]==response){yahooTracking.ult_tracking("ultplact",{'clicktracking':false,'val1':response,'val2':responseLength});if(responseLength>=0&&responseLength<=MAX_ERROR_PAGE_SIZE){aSubject.cancel(Components.results.NS_BINDING_ABORTED);var regex1=new RegExp(/[a-z]*\.toolbar\.yahoo\.com\/bh\/[a-z]*[0-9]*\/epa/);var regex2=new RegExp(/[a-z]*[0-9]*\.search\.yahoo\.com/);var regex3=new RegExp(/404handler/);if((url.match(regex1))||(url.match(regex2)&&url.match(regex3)))return;win.document.location=(_self.navAssistBaseUrl+"&url="+escape(url)+"&error="+response);break;}}}}}}}
catch(e){}};this.initialize=function(){try{var obsService=Components.classes['@mozilla.org/observer-service;1'].getService(Components.interfaces.nsIObserverService);var yahooLocalStorage=Components.classes["@yahoo.com/localstorage;1"].getService(Components.interfaces.nsIYahooLocalStorage);_configMgr.addOnChangeListener("general.navassist",this);var intl=_configMgr.getCharValue("installer.language");if(!intl)intl='us';_errorsToTrap.push(404);_errorsToTrap.push(512);_self.navAssistBaseUrl="http://"+yahooLocalStorage.getString("yahoo.ytff.dataserver.url")+"/bh/v2/epa/?.sc="
+_configMgr.getCharValue('toolbar.sc')
+"&.tc="+_configMgr.getCharValue('toolbar.tc');+"&.intl="+intl;+"&.cv="+_configMgr.getCharValue("installer.version");obsService.addObserver(this,"yahoo-feed-updated",false);if(_configMgr.getBoolValue("general.navassist")){obsService.addObserver(this,"http-on-examine-response",false);}}
catch(e){yahooError(e);}};this.uninitialize=function(){try{var obsService=Components.classes['@mozilla.org/observer-service;1'].getService(Components.interfaces.nsIObserverService);obsService.removeObserver(this,"yahoo-feed-updated");if(_configMgr.getBoolValue("general.navassist"))
obsService.removeObserver(this,"http-on-examine-response");}
catch(e){yahooError(e);}};};Yahoo404Converter.prototype={classID:Components.ID("{2c5b1520-ec6d-11dd-ba2f-0800200c9a66}"),contractID:"@yahoo.com/navassist;1",QueryInterface:XPCOMUtils.generateQI([Components.interfaces.nsIObserver,Components.interfaces.nsIYahooNavAssist])};if(XPCOMUtils.generateNSGetFactory)
var NSGetFactory=XPCOMUtils.generateNSGetFactory([Yahoo404Converter]);else
var NSGetModule=XPCOMUtils.generateNSGetModule([Yahoo404Converter]);