
Components.utils.import("resource://gre/modules/XPCOMUtils.jsm");var Cc=Components.classes;var Ci=Components.interfaces;var loader=Cc["@mozilla.org/moz/jssubscript-loader;1"].getService(Ci.mozIJSSubScriptLoader);loader.loadSubScript("chrome://ytoolbar/content/utils.js");loader.loadSubScript("chrome://ytoolbar/content/logger.js");const YAHOO_TICKER_ALERT_ID=210;const YAHOO_PAR_TICKER_ALERT_ID=211;var gObserverService=Cc['@mozilla.org/observer-service;1'].getService(Ci.nsIObserverService);var gLocalstorage=null;var gSkinParams={skin_fin_tick_text:"#D3D3D3",skin_fin_tick_unch:"#FFFFFF",skin_fin_tick_gain:"#66CC33",skin_fin_tick_loss:"#FF6666",skin_spt_tick_score:"#FDA046",skin_spt_tick_overs:"#AEAEAE"};function WrapperClass(object){this.wrappedJSObject=this;this.object=object;}
WrapperClass.prototype={QueryInterface:function(iid){if(!iid.equals(Components.interfaces.nsISupports)){throw Components.results.NS_ERROR_NO_INTERFACE;}
return this;}};function YahooTicker(){var _mTimer=Cc['@mozilla.org/timer;1'].createInstance(Ci.nsITimer);var _self=this;var _mActiveTimer=false;this.btnId="";this.rotateInterval=7000;this.alertId="";this.currentIndex=0;this.observe=function(aSubject,aTopic,aData){if(aTopic=="timer-callback"){try{var alrtData=gLocalstorage.getObject(_self.alertId);var foundEntries=false;if(alrtData){alrtData=alrtData.wrappedJSObject.object;if(alrtData){alrtData=alrtData[1];if(alrtData.tick_entries){var obj=alrtData.tick_entries[_self.currentIndex];if(obj){obj.doAnim=alrtData.tick_entries.length>1?true:false;for(var name in gSkinParams){obj.text=obj.text.replace(new RegExp("@"+name,"ig"),gSkinParams[name]);}
foundEntries=true;gObserverService.notifyObservers(new WrapperClass(obj),"yahoo-ticker-manager-rotate",_self.btnId);_self.currentIndex=(++_self.currentIndex%alrtData.tick_entries.length);}}}}
if(!foundEntries)
gObserverService.notifyObservers(null,"yahoo-ticker-manager-reset",_self.btnId);}catch(e){_self.currentIndex=0;}}}
this.start=function(){if(_mActiveTimer==false){_mTimer.init(this,_self.rotateInterval,Ci.nsITimer.TYPE_REPEATING_SLACK);_mActiveTimer=true;}}
this.stop=function(){if(_mActiveTimer==true){_mTimer.cancel();_mActiveTimer=false;}}
this.QueryInterface=function(aIID){if(aIID.equals(Ci.nsIObserver)||aIID.equals(Ci.nsISupports)){return this;}
throw Components.results.NS_ERROR_NO_INTERFACE;}}
function YahooTickerManager(){var _mTickerButtons=[];var _mParTickerButtons=[];var _mToolbarManager=null;this.TICKER_ALERT_ID=YAHOO_TICKER_ALERT_ID;this.TICKER_PAR_ALERT_ID=YAHOO_PAR_TICKER_ALERT_ID;this.getTickerButtonIds=function(){var retVal=[];for(var i in _mTickerButtons){retVal.push(_mTickerButtons[i].btnId);}
return retVal.join(",");}
this.getParTickerButtonIds=function(){var retVal=[];for(var i in _mParTickerButtons){retVal.push(_mParTickerButtons[i].btnId);}
return retVal.join(",");}
this.init=function(toolbarManager){gLocalstorage=Cc["@yahoo.com/localstorage;1"].getService(Ci.nsIYahooLocalStorage);_mToolbarManager=toolbarManager;gObserverService.addObserver(this,"yahoo-feed-updated",false);}
this.uninit=function(){gObserverService.removeObserver(this,"yahoo-feed-updated");}
this.observe=function(aSubject,aTopic,aData){try{if(aTopic=="yahoo-feed-updated"){var skindata=gLocalstorage.getObject("yahoo-toolbar-skin.yhash");if(skindata){skindata=skindata.wrappedJSObject.object;gSkinParams.skin_fin_tick_gain=skindata.skin_fin_tick_gain?skindata.skin_fin_tick_gain:gSkinParams.skin_fin_tick_gain;gSkinParams.skin_fin_tick_loss=skindata.skin_fin_tick_loss?skindata.skin_fin_tick_loss:gSkinParams.skin_fin_tick_loss;gSkinParams.skin_fin_tick_text=skindata.skin_fin_tick_text?skindata.skin_fin_tick_text:gSkinParams.skin_fin_tick_text;gSkinParams.skin_fin_tick_unch=skindata.skin_fin_tick_unch?skindata.skin_fin_tick_unch:gSkinParams.skin_fin_tick_unch;gSkinParams.skin_spt_tick_overs=skindata.skin_spt_tick_overs?skindata.skin_spt_tick_overs:gSkinParams.skin_spt_tick_overs;gSkinParams.skin_spt_tick_score=skindata.skin_spt_tick_score?skindata.skin_spt_tick_score:gSkinParams.skin_spt_tick_score;}
for(var i in _mTickerButtons){_mTickerButtons[i].stop();}
for(var i in _mParTickerButtons){_mParTickerButtons[i].stop();}
_mTickerButtons.splice(0,_mTickerButtons.length);_mParTickerButtons.splice(0,_mParTickerButtons.length);var layout=_mToolbarManager.getLayoutButtons("");layout+=","+_mToolbarManager.getLayoutButtons(_mToolbarManager.getGroupButtonId());layout=layout.split(",");layout=yahooUtils.deDupe(layout);for(var i in layout){var btnHash=gLocalstorage.getObject("yahoo-toolbar-"+layout[i]+".yhash");if(btnHash){btnHash=btnHash.wrappedJSObject.object;if(btnHash){if(btnHash.alrt&&btnHash.alrt.indexOf(YAHOO_TICKER_ALERT_ID)>=0){var ticker=new YahooTicker();ticker.btnId=layout[i];ticker.rotateInterval=btnHash.rot_delay?btnHash.rot_delay:ticker.rotateInterval;ticker.alertId=YAHOO_TICKER_ALERT_ID+"_"+layout[i];_mTickerButtons.push(ticker);ticker.start();}
else if(btnHash.alrt&&btnHash.alrt.indexOf(YAHOO_PAR_TICKER_ALERT_ID)>=0){var ticker=new YahooTicker();ticker.btnId=layout[i];ticker.rotateInterval=btnHash.rot_delay?btnHash.rot_delay:ticker.rotateInterval;ticker.alertId=YAHOO_PAR_TICKER_ALERT_ID+"_"+layout[i];_mParTickerButtons.push(ticker);ticker.start();}}}}}}catch(e){yahooError(e);}}}
YahooTickerManager.prototype={classID:Components.ID("{3B211AB0-62FA-4A13-B948-4862683E6DAF}"),contractID:"@yahoo.com/tickermanager;1",QueryInterface:XPCOMUtils.generateQI([Components.interfaces.nsIObserver,Components.interfaces.nsIYahooTickerManager])};if(XPCOMUtils.generateNSGetFactory)
var NSGetFactory=XPCOMUtils.generateNSGetFactory([YahooTickerManager]);else
var NSGetModule=XPCOMUtils.generateNSGetModule([YahooTickerManager]);