
Components.utils.import("resource://gre/modules/XPCOMUtils.jsm");var loader=Components.classes["@mozilla.org/moz/jssubscript-loader;1"].getService(Components.interfaces.mozIJSSubScriptLoader);loader.loadSubScript("chrome://ytoolbar/content/utils.js");loader.loadSubScript("chrome://ytoolbar/content/logger.js");function yMailSingleInstance(){};yMailSingleInstance.prototype={mEnabled:true,mCurrentInstance:null,mCurrentTab:null,mCurrentWindow:null,mYMailPrefBranchName:"options.mailsi.userenable",mYMailEnable:"options.mailsi.enable",mYMailCandyGramUrl:"yahoo.com/dc/launch",mYMailRoot:"mail.yahoo.com",mDirectUrlList:[],mRedirectUrlList:[],mIgnoreUrlList:[],mHandlingRedirect:false,mRedirectChecker:null,openMail:function(uri){if(this.mCurrentInstance){this.mCurrentInstance.contentWindow.wrappedJSObject._TBCD(uri);}},cancelAndSetUserUri:function(aSubject){aSubject.loadFlags=Components.interfaces.nsICachingChannel.LOAD_ONLY_FROM_CACHE;aSubject.cancel(Components.results.NS_BINDING_ABORTED);var yConfMgr=Components.classes["@yahoo.com/configmanager;1"].getService(Components.interfaces.nsIYahooConfigManager);yConfMgr.isYahooKey=false;var url=yConfMgr.getCharValue('browser.startup.homepage');if(this.isUriToMail(url,false)||url.indexOf("mail.yahoo.com")!=-1||url.indexOf("resource:")===0){var intl=yConfMgr.getCharValue("installer.language");url="http://"+(intl?intl:"us")+".search.yahoo.com/";}
if(!aSubject.notificationCallbacks){return;}
var interfaceRequestor=aSubject.notificationCallbacks.QueryInterface(Components.interfaces.nsIInterfaceRequestor);var win=interfaceRequestor.getInterface(Components.interfaces.nsIDOMWindow);if(!win){return;}
var targetDoc=win.document;if(targetDoc&&targetDoc.location=="about:blank"&&url!==""){targetDoc.location=url;}},observe:function(aSubject,aTopic,aData){try{if(aTopic==="http-on-modify-request"){if(this.mHandlingRedirect){return;}
aSubject.QueryInterface(Components.interfaces.nsIHttpChannel);if(!aSubject.notificationCallbacks){return}
if(!aSubject.notificationCallbacks.QueryInterface(Components.interfaces.nsIInterfaceRequestor).getInterface(Components.interfaces.nsIDOMWindow)){return;}
var doneBegin=aSubject.URI.spec.indexOf(".done");if(doneBegin>=0&&doneBegin<aSubject.URI.spec.indexOf(this.mYMailRoot)){return;}
if(this.isUriToMail(aSubject.URI.spec,true)){if(!this.isMailInstanceOpen()){return;}
this.mHandlingRedirect=true;this.cancelAndSetUserUri(aSubject);var _self=this;var redirectCheckRequestor={onStartRequest:function(request,context){},onStopRequest:function(request,context,statusCode){_self.mHandlingRedirect=false;if(_self.isMailInstanceOpen()){_self.focusCurrentInstance();_self.openMail(request.name);}else{_self.openURI(request.name);}}};this.mRedirectChecker.init(aSubject.URI);this.mRedirectChecker.loadFlags=Components.interfaces.nsIRequest.LOAD_BYPASS_CACHE;this.mRedirectChecker.asyncCheck(redirectCheckRequestor,null);this.focusCurrentInstance();}else if(this.isUriToMail(aSubject.URI.spec,false)){if(!this.isMailInstanceOpen()){return;}
this.cancelAndSetUserUri(aSubject);var _self=this;yahooUtils.setTimeout(function(){_self.focusCurrentInstance();},500);}}else if(aTopic==="yahoo-feed-updated"){var localStorage=Components.classes["@yahoo.com/localstorage;1"].getService(Components.interfaces.nsIYahooLocalStorage);var yConfMgr=Components.classes["@yahoo.com/configmanager;1"].getService(Components.interfaces.nsIYahooConfigManager);var hash=localStorage.getObject("yahoo-toolbar-ymsi.yhash");if(hash){var hash=hash.wrappedJSObject.object;if(hash){yConfMgr.setBoolValue(this.mYMailEnable,true,true);this.mYMailCandyGramUrl=hash.ymailcg;this.mYMailRoot=hash.ymailroot;hash.directservers=hash.directservers.replace(/\\\\u0001/g,"\x01");hash.directservers=hash.directservers.replace(/\\\\u0002/g,"\x02");hash.redirectservers=hash.redirectservers.replace(/\\\\u0001/g,"\x01");hash.redirectservers=hash.redirectservers.replace(/\\\\u0002/g,"\x02");hash.ignoreservers=hash.ignoreservers.replace(/\\\\u0001/g,"\x01");hash.ignoreservers=hash.ignoreservers.replace(/\\\\u0002/g,"\x02");hash.directservers=hash.directservers.replace(/\\\\/g,"");hash.directservers=hash.directservers.replace(/\x02/g,"\&");hash.redirectservers=hash.redirectservers.replace(/\\\\/g,"");hash.redirectservers=hash.redirectservers.replace(/\x02/g,"\&");hash.ignoreservers=hash.ignoreservers.replace(/\\\\/g,"");hash.ignoreservers=hash.ignoreservers.replace(/\x02/g,"\&");this.mDirectUrlList=hash.directservers.split(/\x01/);this.mRedirectUrlList=hash.redirectservers.split(/\x01/);this.mIgnoreUrlList=hash.ignoreservers.split(/\x01/);}else{yConfMgr.setBoolValue(this.mYMailEnable,false,true);this.uninitialize();}}else{yConfMgr.setBoolValue(this.mYMailEnable,false,true);this.uninitialize();}}}catch(e){}},isMailInstanceOpen:function(){var wm=Components.classes["@mozilla.org/appshell/window-mediator;1"].getService(Components.interfaces.nsIWindowMediator);var browserEnumerator=wm.getEnumerator("navigator:browser");while(browserEnumerator.hasMoreElements()){var browserWindow=browserEnumerator.getNext();var browserInstance=browserWindow.getBrowser();var numTabs=browserInstance.tabContainer.childNodes.length;for(var index=0;index<numTabs;index++){var currentUrl=browserInstance.getBrowserAtIndex(index).currentURI.spec;if(currentUrl.indexOf(this.mYMailCandyGramUrl)!=-1){this.mCurrentTab=browserInstance.tabContainer.childNodes[index];this.mCurrentInstance=browserInstance;this.mCurrentWindow=browserWindow;return true;}}}
this.mCurrentTab=null;this.mCurrentInstance=null;this.mCurrentWindow=null;return false;},isUriToMail:function(uri,includeRDuri){var bRetVal=false;var idx=0;if(!includeRDuri){for(idx=0;idx<this.mDirectUrlList.length;idx++){if(uri.search(this.mDirectUrlList[idx])!=-1){bRetVal=true;break;}}}else{for(idx=0;idx<this.mRedirectUrlList.length;idx++){if(uri.search(this.mRedirectUrlList[idx])!=-1){bRetVal=true;break;}}}
if(bRetVal){for(idx=0;idx<this.mIgnoreUrlList.length;idx++){if(uri.search(this.mIgnoreUrlList[idx])!=-1){bRetVal=false;break;}}}
return bRetVal;},focusCurrentInstance:function(){if(!this.mCurrentTab){return;}
this.mCurrentInstance.selectedTab=this.mCurrentTab;this.mCurrentWindow.focus();},openURI:function(uri){var recentWindow=Components.classes["@mozilla.org/appshell/window-mediator;1"].getService(Components.interfaces.nsIWindowMediator).getMostRecentWindow("navigator:browser");if(recentWindow){recentWindow.delayedOpenTab(uri,null,null,null,null);}},initialize:function(){var yConfMgr=Components.classes["@yahoo.com/configmanager;1"].getService(Components.interfaces.nsIYahooConfigManager);var ObsServ=Components.classes["@mozilla.org/observer-service;1"].getService(Components.interfaces.nsIObserverService);ObsServ.addObserver(this,"yahoo-feed-updated",false);this.mEnabled=yConfMgr.getBoolValue(this.mYMailPrefBranchName);if(!yConfMgr.getBoolValue(this.mYMailEnable)&&this.mEnabled){this.mEnabled=false;}
if(this.mEnabled){ObsServ.addObserver(this,"http-on-modify-request",false);this.mRedirectChecker=Components.classes["@mozilla.org/network/urichecker;1"].createInstance(Components.interfaces.nsIURIChecker);}},uninitialize:function(){if(!this.mEnabled){return;}
Components.classes["@mozilla.org/observer-service;1"].getService(Components.interfaces.nsIObserverService).removeObserver(this,"http-on-modify-request");this.mRedirectChecker=null;this.mEnabled=false;},classID:Components.ID("{4BA5E994-051E-4327-B654-7AAADC7D4F97}"),contractID:"@yahoo.com/singleinstance;1",QueryInterface:XPCOMUtils.generateQI([Components.interfaces.nsIObserver,Components.interfaces.nsIYahooMailSingleInstance])};if(XPCOMUtils.generateNSGetFactory)
var NSGetFactory=XPCOMUtils.generateNSGetFactory([yMailSingleInstance]);else
var NSGetModule=XPCOMUtils.generateNSGetModule([yMailSingleInstance]);