
Components.utils.import("resource://gre/modules/XPCOMUtils.jsm");var yahooCI=Components.interfaces;var yahooCC=Components.classes;var loader=yahooCC["@mozilla.org/moz/jssubscript-loader;1"].getService(yahooCI.mozIJSSubScriptLoader);loader.loadSubScript("chrome://ytoolbar/content/logger.js");loader.loadSubScript("chrome://ytoolbar/content/utils.js");function WrapperClass(object){this.wrappedJSObject=this;this.object=object;}
WrapperClass.prototype={QueryInterface:function(iid){if(!iid.equals(yahooCI.nsISupports)){throw Components.results.NS_ERROR_NO_INTERFACE;}
return this;}};function YahooPluginCallback(){try{var ACTIONTYPE_NAVIGATE;var ACTIONTYPE_SHOW_DROPDOWN;var EVENTTYPE_BROWSER;var EVENTTYPE_UI;this.ACTIONTYPE_NAVIGATE="NAVIGATE";this.ACTIONTYPE_SHOW_DROPDOWN="SHOW_DROPDOWN";this.EVENTTYPE_BROWSER="BROWSER";this.EVENTTYPE_UI="UI";this.yObsSvc=yahooCC["@mozilla.org/observer-service;1"].getService(yahooCI.nsIObserverService);this.yLocalStorage=yahooCC["@yahoo.com/localstorage;1"].getService(yahooCI.nsIYahooLocalStorage);this.yConfMgr=yahooCC["@yahoo.com/configmanager;1"].getService(yahooCI.nsIYahooConfigManager);}catch(e){yahooError(e);}}
YahooPluginCallback.prototype={test_xml:"",observe:function(aSubject,aTopic,aData){try{yahooDebug("YahooPluginCallback::observe()");}catch(e){yahooError("YahooPluginCallback::observe::"+e);}},getObject:function(InterfaceID,CLSID){var XPCOMObject=null;try{if(!this.isInterfaceAccessible(InterfaceID,CLSID)){return null;}
var wm=Components.classes["@mozilla.org/appshell/window-mediator;1"].getService(Components.interfaces.nsIWindowMediator);var navWin=null;var navNav=null;switch(InterfaceID)
{case"nsIDOMWindowInternal":navWin=wm.getMostRecentWindow("navigator:browser");XPCOMObject=navWin;break;case"nsIDOMWindow":navWin=wm.getMostRecentWindow("navigator:browser");if(navWin.top==null){yahooDebug("got a null nsIDOMWindow");}
XPCOMObject=navWin.top;break;case"nsIWebNavigation":navWin=wm.getMostRecentWindow("navigator:browser");navNav=navWin.QueryInterface(nsIInterfaceRequestor).getInterface(nsIWebNavigation);XPCOMObject=navNav;break;default:XPCOMObject=null;break;}}catch(e){yahooError(e);}
return XPCOMObject;},UpdateUI:function(CLSID){try{this.yObsSvc.notifyObservers(null,"yahoo-partner-update-call",CLSID);}catch(e){yahooError("YahooPluginCallback.UpdateUI()::"+e);}},getValue:function(keyXML){var retVal;try{var btnHashJSON=yahooUtils.JSON.parse(this.yConfMgr.getCharValue("partner.hash"));switch(keyXML)
{case"id":retVal=btnHashJSON.id;break;case"pc":retVal=this.yConfMgr.getCharValue("toolbar.pc");break;case"dc":retVal=this.yConfMgr.getCharValue("toolbar.dc");break;case"tc":retVal=this.yConfMgr.getCharValue("toolbar.tc");break;case"intl":retVal=this.yConfMgr.getCharValue("installer.language");break;case"ver":retVal=this.yConfMgr.getCharValue("installer.version.simple");break;case"n_st":retVal=btnHashJSON.n_st;break;case"url":try{var wm=Components.classes["@mozilla.org/appshell/window-mediator;1"].getService(Components.interfaces.nsIWindowMediator);var navWin=wm.getMostRecentWindow("navigator:browser");var topWinBrowser=navWin.getBrowser();retVal=topWinBrowser.getBrowserForTab(topWinBrowser.selectedTab).currentURI.spec;}catch(e){retVal="about:blank";yahooError("Error: YahooPluginCallback.getValue()::Faled to get the URL");}
break;case"hwnd":retVal=null;break;default:retVal="";break;}
if(keyXML.indexOf("si_")>-1){switch(keyXML)
{case"si_0":retVal=btnHashJSON.si_0;break;case"si_1":retVal=btnHashJSON.si_1;break;case"si_2":retVal=btnHashJSON.si_2;break;case"si_3":retVal=btnHashJSON.si_3;break;case"si_4":retVal=btnHashJSON.si_4;break;}}}catch(e){retVal="";yahooError("YahooPluginCallback.getValue()::"+e);}
return retVal;},setValue:function(keyXML){try{yahooDebug("YahooPluginCallback::setValue()");}catch(e){yahooError("YahooPluginCallback.setValue()::"+e);}},handleAction:function(eventArgXML){try{yahooDebug("YahooPluginCallback::handleAction()");}catch(e){yahooError("YahooPluginCallback.handleAction()::"+e);}
return true;},requestAction:function(actionType,eventArgXML){try{var xmlParser=yahooCC["@mozilla.org/xmlextras/domparser;1"].createInstance(yahooCI.nsIDOMParser);var xmlArgs=xmlParser.parseFromString(eventArgXML,"text/xml");if(xmlArgs.tagName==="parserError"){return;}
switch(actionType)
{case this.ACTIONTYPE_NAVIGATE:var navigationURL="";var navigationWin="";var Args=xmlArgs.getElementsByTagName("Arg");for(var idx=0;idx<Args.length;idx++){var Arg=Args[idx];if(Arg.getAttribute("name")=="url"){navigationURL=Arg.getAttribute("value");}
if(Arg.getAttribute("name")=="flags"){navigationWin=Arg.getAttribute("value");}}
var wm=Components.classes["@mozilla.org/appshell/window-mediator;1"].getService(Components.interfaces.nsIWindowMediator);var navWin=wm.getMostRecentWindow("navigator:browser");if(navigationWin=="newTab"){navWin.getBrowser().addTab(navigationURL);}else{navWin.getBrowser().loadURI(navigationURL);}
break;case this.ACTIONTYPE_SHOW_DROPDOWN:break;default:break;}}catch(e){yahooError("YahooPluginCallback.requentAction()::"+e);}},subscribeEvent:function(eventType,CLSID){try{if(eventType==this.EVENTTYPE_BROWSER){this.yLocalStorage.putString(CLSID+"_BROWSEREVENTS",true);}}catch(e){yahooError("YahooPluginCallback.subscribeEvent()::"+e);}},isInterfaceAccessible:function(InterfaceID,CLSID){try{var supportedInterface="nsIDOMWindowInternal,nsIDOMWindow,nsIWebNavigation";if(this.yLocalStorage.getString(CLSID)!=null&&this.yLocalStorage.getString(CLSID)!=""){supportedInterface=this.yLocalStorage.getString(CLSID)}
if(supportedInterface.indexOf(InterfaceID)>-1){return true;}else{return false;}}catch(e){yahooError("YahooPluginCallback.isInterfaceAccessible()::"+e);}},classID:Components.ID("{a5178fa0-7838-11de-8a39-0800200c9a66}"),contractID:"@yahoo.com/yplugincallback;1",QueryInterface:XPCOMUtils.generateQI([Components.interfaces.nsIYahooPluginCallback])};if(XPCOMUtils.generateNSGetFactory)
var NSGetFactory=XPCOMUtils.generateNSGetFactory([YahooPluginCallback]);else
var NSGetModule=XPCOMUtils.generateNSGetModule([YahooPluginCallback]);