
Components.utils.import("resource://gre/modules/XPCOMUtils.jsm");var yahooCI=Components.interfaces;var yahooCC=Components.classes;var loader=yahooCC["@mozilla.org/moz/jssubscript-loader;1"].getService(yahooCI.mozIJSSubScriptLoader);loader.loadSubScript("chrome://ytoolbar/content/logger.js");loader.loadSubScript("chrome://ytoolbar/content/utils.js");function WrapperClass(object){this.wrappedJSObject=this;this.object=object;}
WrapperClass.prototype={QueryInterface:function(iid){if(!iid.equals(yahooCI.nsISupports)){throw Components.results.NS_ERROR_NO_INTERFACE;}
return this;}};function YahooPluginManager(){try{this.yLocalStorage=yahooCC["@yahoo.com/localstorage;1"].getService(yahooCI.nsIYahooLocalStorage);this.yObsSvc=yahooCC["@mozilla.org/observer-service;1"].getService(yahooCI.nsIObserverService);this.yConfMgr=yahooCC["@yahoo.com/configmanager;1"].getService(yahooCI.nsIYahooConfigManager);this.yPluginCallback=yahooCC["@yahoo.com/yplugincallback;1"].getService(yahooCI.nsIYahooPluginCallback);this.yCache=yahooCC["@yahoo.com/ycache;1"].getService(yahooCI.nsIYahooCache);this.yFileIO=yahooCC["@yahoo.com/fileio;1"].getService(yahooCI.nsIYahooFileIO2);this.headerInfo="";this.Init();}catch(e){yahooError(e);}}
YahooPluginManager.prototype={plugInMap:[],headerInfo:"",attributeMap:"",buttonMap:"",plugIns:[],bWaiting:false,lastxmlResponse:"",lastURL:"",lastUsedTab:null,plugInData:[],bParsingInProgress:false,key:"",Init:function(){try{this.yObsSvc.addObserver(this,"yahoo-feed-updated",false);this.yObsSvc.addObserver(this,"yahoo-partner-update-call",false);this.yObsSvc.addObserver(this,"yahoo-browser_navigation-cancelled",false);this.yObsSvc.addObserver(this,"http-on-modify-request",false);this.headerInfo="<? xml version='1.0' encoding='UTF-8'?>";this.headerInfo+="<YTBRoot id='ytbHeader' version='1.0'><YTBHeader>";this.headerInfo+="<BrowserInfo><browser>FF</browser><version>3.1</version></BrowserInfo>";this.headerInfo+="<TBInfo><tbversion>"+this.yConfMgr.getCharValue("installer.version.simple")+"</tbversion>";this.headerInfo+="<country>"+this.yConfMgr.getCharValue("installer.country")+"</country>";this.headerInfo+="<language>"+this.yConfMgr.getCharValue("installer.language")+"</language>";this.headerInfo+="</TBInfo></YTBHeader></YTBRoot>";this.loadFromCache();this.loadUnloadPartners();if(this.yConfMgr.isKeyPresent("att.isEnabled")){this.isEnabled=this.yConfMgr.getBoolValue("att.isEnabled");}else{this.isEnabled=true;}
this.bParsingInProgress=false;}catch(e){yahooError("YahooPluginManager::Init()::"+e);}},observe:function(aSubject,aTopic,aData){try{if(aTopic==="yahoo-feed-updated"){var thisPluginMgr=this;this.yObsSvc.notifyObservers(null,"yahoo-partner-ui-found",this.key);yahooUtils.setTimeout(function(){thisPluginMgr.loadUnloadPartners();},300);}
else if(aTopic==="yahoo-partner-update-call"){var thisPluginMgr=this;yahooUtils.setTimeout(function(){thisPluginMgr.refreshPartnerButtons(aData);},200);}
else if(aTopic==="yahoo-browser_navigation-cancelled"){this.onNavigationCancelled();}
else if(aTopic==="http-on-modify-request"){aSubject.QueryInterface(Components.interfaces.nsIHttpChannel);if(!(aSubject.loadFlags&aSubject.LOAD_INITIAL_DOCUMENT_URI))return;var url=aSubject.URI.spec;var browserTab=this.getBrowserFromChannel(aSubject);if(browserTab==null){browserTab=this.getSelectedTab();}
if(browserTab!=null){this.lastUsedTab=browserTab;var bNavigate=this.onBeforeNavigate(url,false);this.lastUsedTab.setAttribute("obn","showing");if(!bNavigate){this.lastUsedTab.setAttribute("obn","cancelled");aSubject.cancel(Components.results.NS_BINDING_ABORTED);}else{this.lastUsedTab.setAttribute("obn","granted");this.lastUsedTab.setAttribute("ypageurl",url);}
this.lastUsedTab.setAttribute("yurl",url);this.lastUsedTab.setAttribute("ydt",this.getCurrentDate());}}}catch(e){yahooError("YahooPluginManager::observe::"+e);}},loadPartnerPlugIn:function(CLSID){var _partnerBridge=null;try{_partnerBridge=yahooCC["@yahoo.com/ytbxpcom;1"].createInstance(yahooCI.nsIYTBXPCOM);if(_partnerBridge!=null){_partnerBridge.Init(CLSID,this.yPluginCallback);this.plugIns.push(_partnerBridge);}}catch(e){yahooError("YahooPluginManager::loadPartnerPlugIn::"+e);}
return _partnerBridge;},loadUnloadPartners:function(){try{if(this.yConfMgr.getCharValue("ypluginids")!=""){this.plugInMap=this.yConfMgr.getCharValue("ypluginids").split(",");}
try{for(var idx=0;idx<this.plugInMap.length;idx++){if(!this.isPartnerLoaded(this.plugInMap[idx])){var _partnerBridge=yahooCC["@yahoo.com/ytbxpcom;1"].createInstance(yahooCI.nsIYTBXPCOM);if(_partnerBridge!=null){_partnerBridge.Init(this.plugInMap[idx],this.yPluginCallback);this.plugIns.push(_partnerBridge);}else{yahooDebug("Failed to create XPCOM Bridge...");}}}}catch(e){yahooError("YahooPluginManager::loadUnloadPartners.PartnerBridge().Init()"+e);}
this.unloadPartners(false);this.refreshAllPartners();}catch(e){yahooError("YahooPluginManager::loadUnloadPartners()"+e);}},unloadPartners:function(bAllPartners)
{try{if(bAllPartners){for(var idx=0;idx<this.plugIns.length;idx++){this.plugIns[idx].Destroy();}}
this.writeToCache();}catch(e){yahooError(e);}},isPartnerLoaded:function(CLSID){try{var isLoaded=false;for(var idx=0;idx<this.plugIns.length;idx++){var this_clsid=new Object();try{this.plugIns[idx].GetPartnerID(this_clsid);if(this_clsid.value===CLSID){isLoaded=true;break;}}catch(e1){yahooError(e1);}}}catch(e){yahooError(e);}
return isLoaded;},getPlugIn:function(CLSID){var oPlugIn=null;try{for(var idx=0;idx<this.plugIns.length;idx++){var this_clsid=new Object();try{this.plugIns[idx].GetPartnerID(this_clsid);if(this_clsid.value===CLSID){oPlugIn=this.plugIns[idx];}}catch(e1){yahooError(e1);}}}catch(e){yahooError(e);}
return oPlugIn;},refreshPartnerButtons:function(CLSID){if(this.bParsingInProgress){return;}else{this.bParsingInProgress=true;}
try{this.attributeMap="{ \"buttons\" : [";this.buttonMap="{ \"buttonMap\" : [";var oPlugIn=this.getPlugIn(CLSID);if(oPlugIn){var buttonData=new Object();var this_clsid=new Object();oPlugIn.GetPartnerID(this_clsid);var buttoninfo=this.getPartnerButtonXML(this_clsid.value);oPlugIn.GetData(this.headerInfo,buttoninfo,buttonData);this.lastxmlResponse=buttonData.value.replace(/&/g,"&amp;");this.attData(this.lastxmlResponse);this.parseData(CLSID,this.lastxmlResponse);}
this.attributeMap=this.attributeMap.substr(0,this.attributeMap.length-1);this.attributeMap+="]}";this.yLocalStorage.putString("yDOMAttributes",this.attributeMap);this.buttonMap=this.buttonMap.substr(0,this.buttonMap.length-1);this.buttonMap+="]}";this.yLocalStorage.putString("yPtnrBtnMap",this.buttonMap);if(this.buttonMap.length<=18){}else{this.saveButtonXML("");this.notifyTabs(true);}}catch(e){yahooError(e);}
this.bParsingInProgress=false;},refreshAllPartners:function(){if(this.bParsingInProgress){return;}else{this.bParsingInProgress=true;}
try{var key="";this.attributeMap="{ \"buttons\" : [";this.buttonMap="{ \"buttonMap\" : [";if(this.plugIns.length<=0){return;}
for(var idx=0;idx<this.plugIns.length;idx++){try{var buttonData=new Object();var this_clsid=new Object();this.plugIns[idx].GetPartnerID(this_clsid);var buttoninfo=this.getPartnerButtonXML(this_clsid.value);this.plugIns[idx].GetData(this.headerInfo,buttoninfo,buttonData);this.lastxmlResponse=buttonData.value.replace(/&/g,"&amp;");;this.attData(this.lastxmlResponse);this.parseData(this_clsid.value,this.lastxmlResponse);}catch(e1){yahooError("error in retrieving partner data"+e1);}}
this.attributeMap=this.attributeMap.substr(0,this.attributeMap.length-1);this.attributeMap+="]}";this.yLocalStorage.putString("yDOMAttributes",this.attributeMap);this.buttonMap=this.buttonMap.substr(0,this.buttonMap.length-1);this.buttonMap+="]}";this.yLocalStorage.putString("yPtnrBtnMap",this.buttonMap);if(this.buttonMap.length<=18){}else{this.saveButtonXML("");this.notifyTabs(true);}}catch(e){yahooError(e);}
this.bParsingInProgress=false;},parseData:function(CLSID,buttonXML){try{var xmlParser=yahooCC["@mozilla.org/xmlextras/domparser;1"].createInstance(yahooCI.nsIDOMParser);var xmlButton=xmlParser.parseFromString(buttonXML,"text/xml");if(xmlButton.tagName==="parserError"){return;}
var buttons=xmlButton.getElementsByTagName("YButton");for(var idx=0;idx<buttons.length;idx++)
{var button=buttons[idx];this.addToAttributeMap(CLSID,button);var menus=button.getElementsByTagName("YMenu");for(var idxMenu=0;idxMenu<menus.length;idxMenu++){var menu=menus[idxMenu];var parentId=menu.parentNode.getAttribute("id");this.buttonMap+="{ \"id\" : \"yahoo-toolbar-"+parentId+"\" , \"childNodes\" : [";var menuitems=menu.getElementsByTagName("YMenuItem");var menuitemIds="";for(var idy=0;idy<menuitems.length;idy++){var menuitem=menuitems[idy];if(parentId==menuitem.parentNode.parentNode.getAttribute("id")){if(idy>0)menuitemIds+=",";var mType=menuitem.getAttribute("type");if(mType==null||mType==""){mType="item";}
menuitemIds+="\""+mType+"&&"+"yahoo-toolbar-"+menuitem.getAttribute("id")+"\"";this.addToAttributeMap(CLSID,menuitem);}}
menuitemIds=(menuitemIds!="")?menuitemIds:"\"null\"";this.buttonMap+=menuitemIds+"]},";}}}catch(e){yahooError(e);}},addToAttributeMap:function(CLSID,node){var attMap="";var yURL="";var yFunc="31";var yEvent="";var yTrack="";try{if(node.tagName=="YButton"||node.tagName=="YMenuItem"){attMap="{ \"id\" : \"yahoo-toolbar-"+node.getAttribute("id")+"\" , \"attmap\" : [";attMap+="\""+"image"+"%%"+node.getAttribute("icon")+"\"";attMap+=",\""+"label"+"%%"+node.getAttribute("text")+"\"";attMap+=",\""+"tooltiptext"+"%%"+node.getAttribute("tooltip")+"\"";attMap+=",\""+"visible"+"%%"+node.getAttribute("visible")+"\"";if(node.getAttribute("icon")){this.yCache.prefetchURI(node.getAttribute("icon"),true);}
var handler=node.getElementsByTagName("YTBEvent")[0];if(handler){var type=handler.getElementsByTagName("eventType")[0];var handlerType="";if(type){handlerType=type.firstChild.nodeValue}
if(handlerType=="YTB"){yFunc="36";}else{yFunc="31";}
var customArgs="";var eventArgs=handler.getElementsByTagName("eventArgs")[0];if(eventArgs){var Args=eventArgs.getElementsByTagName("Arg");for(var idx=0;idx<Args.length;idx++){var Arg=Args[idx];customArgs+=Arg.getAttribute("name")+"^";customArgs+=Arg.getAttribute("value")+"^^";if(Arg.getAttribute("name")=="url"){yURL=Arg.getAttribute("value");}}
customArgs=customArgs.substr(0,customArgs.length-2);attMap+=",\""+"yevntArgs"+"%%"+customArgs+"\"";}}else{}
yTrack="178060853/"+node.getAttribute("id");yEvent=","+yFunc+","+yTrack+","+yURL;attMap+=",\""+"oncommand"+"%%"+"YAHOO.YTFF.ButtonHandler(event);"+"\"";attMap+=",\""+"yevent"+"%%"+yEvent+"\"";attMap+=",\""+"ytrack"+"%%"+yTrack+"\"";attMap+=",\""+"yurl"+"%%"+yURL+"\"";attMap+=",\""+"yfunc"+"%%"+yFunc+"\"";attMap+=",\""+"yplgin"+"%%"+CLSID+"\"";attMap+="]},";this.attributeMap+=attMap;}}catch(e){yahooError(e);}},getInterface:function(InterfaceID){var XPCOMObject=null;try{var wm=Components.classes["@mozilla.org/appshell/window-mediator;1"].getService(Components.interfaces.nsIWindowMediator);var navWin=null;var navNav=null;switch(InterfaceID)
{case"nsIDOMWindowInternal":navWin=wm.getMostRecentWindow("navigator:browser");XPCOMObject=navWin;break;case"nsIDOMWindow":navWin=wm.getMostRecentWindow("navigator:browser");if(navWin.top==null){yahooDebug("got a null nsIDOMWindow");}
XPCOMObject=navWin.top;break;case"nsIWebNavigation":navWin=wm.getMostRecentWindow("navigator:browser");navNav=navWin.QueryInterface(nsIInterfaceRequestor).getInterface(nsIWebNavigation);XPCOMObject=navNav;break;default:XPCOMObject=null;break;}}catch(e){yahooError(e);}
return XPCOMObject;},handleAction:function(EventSource,CLSID,EventArgs){try{var xmlEventArgs="";EventSource=EventSource.replace("yahoo-toolbar-","");xmlEventArgs+="<?xml version='1.0' encoding='UTF-8'?>";xmlEventArgs+="<YTBRoot id='EventArgs' version='1.0'>";xmlEventArgs+="<YTBEvent>";xmlEventArgs+="<eventSource>"+EventSource+"</eventSource>";xmlEventArgs+="<eventType>UI</eventType>";xmlEventArgs+="<eventID>ONCLICK</eventID>";if(EventArgs!==null&&EventArgs!==""){xmlEventArgs+="<eventArgs>";var customArgs=EventArgs.split("^^");for(idx=0;idx<customArgs.length;idx++){xmlEventArgs+="<Arg name='"+customArgs[idx].split("^")[0]+"' value='"+customArgs[idx].split("^")[1]+"' />"}
xmlEventArgs+="</eventArgs>";}
xmlEventArgs+="</YTBEvent></YTBRoot>";var oPlugIn=this.getPlugIn(CLSID);if(oPlugIn){var retVal=oPlugIn.HandleAction("ONCLICK",xmlEventArgs);}}catch(e){yahooError(e);}},onBrowserEvents:function(EventID,CLSID,EventArgs){var bretVal=true;try{var xmlEventArgs="";xmlEventArgs+="<?xml version='1.0' encoding='UTF-8'?>";xmlEventArgs+="<YTBRoot id='EventArgs' version='1.0'>";xmlEventArgs+="<YTBEvent>";xmlEventArgs+="<eventSource>BROWSER</eventSource>";xmlEventArgs+="<eventType>BROWSER</eventType>";xmlEventArgs+="<eventID>"+EventID+"</eventID>";if(EventArgs!==null&&EventArgs!==""){xmlEventArgs+="<eventArgs>";var customArgs=EventArgs.split("^^");for(idx=0;idx<customArgs.length;idx++){xmlEventArgs+="<Arg name='"+customArgs[idx].split("^")[0]+"' value='"+customArgs[idx].split("^")[1]+"' />"}
xmlEventArgs+="</eventArgs>";}
xmlEventArgs+="</YTBEvent></YTBRoot>";var oPlugIn=this.getPlugIn(CLSID);if(oPlugIn){try{xmlEventArgs=xmlEventArgs.replace(/\&/g,"&amp;");var retVal=oPlugIn.HandleAction(EventID,xmlEventArgs);}catch(e1){yahooDebug(e1);bretVal=false;}}else{yahooDebug("CLSID "+CLSID+" not found...");}}catch(e){yahooError(e);}
return bretVal;},onBeforeNavigate:function(URL,isCurrentTab){try{var retVal=true;var filter_url=["googleads.g.doubleclick","kvmlm2/index.dhtml","website.ws/gditraffic","s7.addthis.com/static/r07/sh33.html"];for(var iful=0;iful<filter_url.length;iful++){if(URL.indexOf(filter_url[iful])>0){return retVal;}}
this.lastURL=URL;if(isCurrentTab){this.lastUsedTab=this.getSelectedTab();}
var schemas=["ftp","file","gopher","about"];var _currentSchema=URL.split(":")[0];if(_currentSchema!=""&&schemas.indexOf(_currentSchema)>=0){this.lastUsedTab=this.getSelectedTab();}
for(var idx=0;idx<this.plugIns.length;idx++){var this_clsid=new Object();this.plugIns[idx].GetPartnerID(this_clsid);var key=this_clsid.value+"_BROWSEREVENTS";var browser_events=(this.yLocalStorage.getString(key)==null)?false:this.yLocalStorage.getString(key);browser_events=true;if(browser_events){this.bWaiting=true;var EventArgs="url^"+URL;retVal=this.onBrowserEvents("BEFORENAVIGATE",this_clsid.value,EventArgs);this.bWaiting=false;}
if(!retVal){break;}else{yahooDebug("Navigation allowed by Plug-in");}}
if(!retVal){yahooUtils.setTimeout(function(){var yObsSvc=yahooCC["@mozilla.org/observer-service;1"].getService(yahooCI.nsIObserverService);yObsSvc.notifyObservers(null,"yahoo-browser_navigation-cancelled",null);},50);}
return retVal;}catch(e){yahooError(e);}},onNavigationCancelled:function(){try{for(var idx=0;idx<this.plugIns.length;idx++){var this_clsid=new Object();this.plugIns[idx].GetPartnerID(this_clsid);var key=this_clsid.value+"_BROWSEREVENTS";var browser_events=(this.yLocalStorage.getString(key)==null)?false:this.yLocalStorage.getString(key);browser_events=true;if(browser_events){var retVal=this.onBrowserEvents("BEFORENAVIGATECANCELLED",this_clsid.value,null);}}}catch(e){yahooError(e);}},onTabChange:function(bBubbleUptoPartners){try{if(this.bWaiting){return;}
var pluginID=this.yConfMgr.getCharValue("ypluginids").split(",")[0];if(pluginID){var _selectedTab=this.getSelectedTab();var obn=_selectedTab.getAttribute("obn")||"";var url=this.getCurrentURL(true);var page_url=_selectedTab.getAttribute("ypageurl")||"about:blank";if(page_url){url=page_url;}
var partnerxml=_selectedTab.getAttribute("ytbPartnerxml");partnerxml=this.attSterilizeDataIfNeeded(url,partnerxml);if(partnerxml&&partnerxml!==""){this.notifyTabs(true);}else{this.lastUsedTab=_selectedTab;this.lastURL=url;var buttoninfo=this.getPartnerButtonXML(pluginID);var partnerxml="";if(!this.isEnabled){partnerxml=buttoninfo.replace("#C_IMAGE",this.yPluginCallback.getValue("si_1"));}else if(url!=""&&this.plugInData.indexOf(url)>=0){partnerxml=buttoninfo.replace("#C_IMAGE",this.yPluginCallback.getValue("si_2"));}else{partnerxml=buttoninfo.replace("#C_IMAGE",this.yPluginCallback.getValue("si_0"));}
this.lastxmlResponse=partnerxml;this.attributeMap="{ \"buttons\" : [";this.buttonMap="{ \"buttonMap\" : [";this.parseData(pluginID,partnerxml);this.attributeMap=this.attributeMap.substr(0,this.attributeMap.length-1);this.attributeMap+="]}";this.yLocalStorage.putString("yDOMAttributes",this.attributeMap);this.buttonMap=this.buttonMap.substr(0,this.buttonMap.length-1);this.buttonMap+="]}";this.yLocalStorage.putString("yPtnrBtnMap",this.buttonMap);this.saveButtonXML("");this.notifyTabs(true);}
if(bBubbleUptoPartners){var EventArgs="url^"+page_url;retVal=this.onBrowserEvents("TABCHANGE",pluginID,EventArgs);}}}catch(e){yahooError(e);}},addToPlugInMap:function(ButtonID,ButtonHash){try{var key="";var oBtnHash=yahooUtils.JSON.parse(ButtonHash);var _clsID=oBtnHash.partner_clsid.replace(/%2D/g,"-");var pluginIDs=this.yConfMgr.getCharValue("ypluginids");if(pluginIDs!=""){if(!(pluginIDs.indexOf(_clsID)>-1))
pluginIDs+=","+_clsID;}else{pluginIDs+=_clsID;}
this.yConfMgr.setCharValue("ypluginids",pluginIDs,true);var _interfaces=(this.yLocalStorage.getString(_clsID)==null)?"":this.yLocalStorage.getString(_clsID);if(oBtnHash.yinterface){_interfaces+=","+oBtnHash.yinterface;this.yLocalStorage.putString(_clsID,_interfaces);}
this.yConfMgr.setCharValue("partner.hash",ButtonHash,true);var key=ButtonID+"^"+_clsID;this.key=key;}catch(e){yahooError(e);}},getCurrentURL:function(bURLXULNode){var retVal="";try{if(bURLXULNode){var wm=Components.classes["@mozilla.org/appshell/window-mediator;1"].getService(Components.interfaces.nsIWindowMediator);var navWin=wm.getMostRecentWindow("navigator:browser");retVal=navWin.document.getElementById("urlbar").value;}}catch(e){yahooError(e);}
return retVal;},getPartnerButtonXML:function(CLSID){try{var key="toolbar."+CLSID;return this.yConfMgr.getCharValue(key);}catch(e){yahooError(e);}},saveButtonXML:function(URL){if(!this.isEnabled){return;}
try{if(this.lastUsedTab==null){this.lastUsedTab=this.getSelectedTab();}
var time_elapased=10000;var current_url=this.getCurrentURL(true);var last_modified_url=this.lastUsedTab.getAttribute("ytbLastURL");var _lastModifiedAt=this.lastUsedTab.getAttribute("ytbLastModifiedAt");if(_lastModifiedAt!=null&&_lastModifiedAt!=""){var _now=new Date();var lastFetched=new Date(_lastModifiedAt);time_elapased=Math.ceil(_now.getTime()-lastFetched.getTime());}
var _domAttributes=this.yLocalStorage.getString("yDOMAttributes");var _buttonMap=this.yLocalStorage.getString("yPtnrBtnMap");this.lastUsedTab.setAttribute("ytbLastURL",this.lastURL);this.lastUsedTab.setAttribute("ytbPartnerxml",this.lastxmlResponse);this.lastUsedTab.setAttribute("ytbButtonMap",_buttonMap);this.lastUsedTab.setAttribute("ytbDOMAttributes",_domAttributes);this.lastUsedTab.setAttribute("ytbLastModifiedAt",this.getCurrentDate());}catch(e){yahooDebug(" saveButtonXML() "+e);}},getSelectedTab:function(){try{var wm=Components.classes["@mozilla.org/appshell/window-mediator;1"].getService(Components.interfaces.nsIWindowMediator);var navWin=wm.getMostRecentWindow("navigator:browser");var topWinBrowser=navWin.getBrowser();return topWinBrowser.getBrowserForTab(topWinBrowser.selectedTab);}catch(e){yahooDebug("getActiveTab() : "+e);}},getBrowserFromChannel:function(aChannel){try{var notificationCallbacks=aChannel.notificationCallbacks?aChannel.notificationCallbacks:aChannel.loadGroup.notificationCallbacks;if(!notificationCallbacks){return null;}
var wm=Components.classes["@mozilla.org/appshell/window-mediator;1"].getService(Components.interfaces.nsIWindowMediator);var _Win=wm.getMostRecentWindow("navigator:browser");var _gBrowser=_Win.getBrowser();var domWin=notificationCallbacks.getInterface(Components.interfaces.nsIDOMWindow);return _gBrowser.getBrowserForDocument(domWin.top.document);}
catch(e){yahooDebug("getBrowserFromChannel(): "+e);return null;}},notifyTabs:function(bAllBrowsers){try{if(bAllBrowsers){yahooUtils.setTimeout(function(){var yObsSvc=yahooCC["@mozilla.org/observer-service;1"].getService(yahooCI.nsIObserverService);yObsSvc.notifyObservers(null,"yahoo-partner-ui-updated",null);},5);}else{if(this.getSelectedTab()==this.lastUsedTab){yahooUtils.setTimeout(function(){var yObsSvc=yahooCC["@mozilla.org/observer-service;1"].getService(yahooCI.nsIObserverService);yObsSvc.notifyObservers(null,"yahoo-partner-ui-updated",null);},5);}}}catch(e){yahooDebug(" notifyTabs() : "+e);}},attData:function(response){try{var state;if(response.indexOf(this.yPluginCallback.getValue("si_0"))>0){state=0;}else if(response.indexOf(this.yPluginCallback.getValue("si_1"))>0){state=1;}else if(response.indexOf(this.yPluginCallback.getValue("si_2"))>0){state=2;}
switch(state){case 0:if(this.plugInData.indexOf(this.lastURL)>0){this.plugInData[this.plugInData.indexOf(this.lastURL)]="";}
this.yConfMgr.setBoolValue("att.isEnabled",true,true);this.isEnabled=true;break;case 1:this.isEnabled=false;this.yConfMgr.setBoolValue("att.isEnabled",false,true);break;case 2:if(this.lastURL!="about:blank"&&this.lastURL.indexOf("file")!=0&&this.plugInData.indexOf(this.lastURL)<0){this.plugInData.push(this.lastURL);}
this.yConfMgr.setBoolValue("att.isEnabled",true,true);this.isEnabled=true;break;default:break;}}catch(e){yahooDebug(e);}},writeToCache:function(){try{var _strdata="";for(var i=0;i<this.plugInData.length;i++){_strdata+=this.plugInData[i]+"^";}
var file=this.yFileIO.getCacheDir();file.appendRelativePath("plugin.data");this.yFileIO.writeUnicodeFile(file,_strdata);}catch(e){yahooDebug(e);}},loadFromCache:function(){try{var _strdata="";var file=this.yFileIO.getCacheDir();file.appendRelativePath("plugin.data");if(file.exists()){_strdata=this.yFileIO.readFile(file);}
var arrTmp=_strdata.split("^");for(var i=0;i<arrTmp.length;i++){if(arrTmp[i]!=""){this.plugInData.push(arrTmp[i]);}}}catch(e){yahooDebug(e);}},attSterilizeDataIfNeeded:function(url,partnerXML){var sterilizedData="";var state;try{if(partnerXML.indexOf(this.yPluginCallback.getValue("si_0"))>0){state=0;}else if(partnerXML.indexOf(this.yPluginCallback.getValue("si_1"))>0){state=1;}else if(partnerXML.indexOf(this.yPluginCallback.getValue("si_2"))>0){state=2;}
switch(state){case 0:if(this.plugInData.indexOf(url)>=0){sterilizedData="";}
break;case 1:sterilizedData=partnerXML;break;case 2:if(this.plugInData.indexOf(url)==-1&&this.plugInData.indexOf(url.substr(0,url.length-1))==-1&&this.plugInData.indexOf(url+"/")==-1){sterilizedData="";}
break;default:sterilizedData=partnerXML;break;}}catch(e){sterilizedData="";yahooDebug(e);}
return sterilizedData;},getCurrentDate:function(){var d=new Date();return d.toUTCString();},classID:Components.ID("{E6CB70A7-53C7-49F0-81B7-08D08220B362}"),contractID:"@yahoo.com/ypluginmanager;1",QueryInterface:XPCOMUtils.generateQI([Components.interfaces.nsIYahooPluginManager])};if(XPCOMUtils.generateNSGetFactory)
var NSGetFactory=XPCOMUtils.generateNSGetFactory([YahooPluginManager]);else
var NSGetModule=XPCOMUtils.generateNSGetModule([YahooPluginManager]);