
Components.utils.import("resource://gre/modules/XPCOMUtils.jsm");try{Components.utils.import("resource://gre/modules/ctypes.jsm")}catch(e){}
var CI=Components.interfaces;var CC=Components.classes;var loader=CC["@mozilla.org/moz/jssubscript-loader;1"].getService(CI.mozIJSSubScriptLoader);var gConfigFilePath="file://"+__LOCATION__.parent.path+"/extconfig.js";loader.loadSubScript(gConfigFilePath);function YLogFormatter(){}
YLogFormatter.prototype={format:function(level,msg,stacktrace){var dt=new Date();var lmsg="["+dt.getTime()+"]";if(level!==null){lmsg+="["+level+"]";}
lmsg+=msg+"\n";if(stacktrace!==null){lmsg+=stacktrace;}
return lmsg;},classID:Components.ID("{80A9F3D2-F4A6-470a-82DC-0921BD206F86}"),contractID:"@yahoo.com/ylogformatter;1",QueryInterface:XPCOMUtils.generateQI([Components.interfaces.nsIYLogFormatter])};function LogCSVFormatter(){this.format=function(level,msg,stacktrace){if(level===null){level="No Level";}
var dt=new Date();var lmsg=+dt.getTime()+","+level+",\""+msg+"\",\""+stacktrace+"\"";return lmsg;};}
LogCSVFormatter.prototype={classID:Components.ID("{99e23411-5afb-4f91-9109-38701fed7ff0}"),contractID:"@yahoo.com/ylogcsvformatter;1",QueryInterface:XPCOMUtils.generateQI([Components.interfaces.nsIYLogFormatter])};function YLogConsoleAppender(){this.mConsole=CC["@mozilla.org/consoleservice;1"].getService(CI.nsIConsoleService);}
YLogConsoleAppender.prototype={mFormatter:null,mModuleName:null,mName:"ConsoleAppender",mConsole:null,init:function(modulename){this.mModuleName=modulename;},setName:function(name){this.mName=name;},getName:function(name){return this.mName;},setFormatter:function(formatter){this.mFormatter=formatter;},append:function(level,message,stacktrace){var msg="";if(this.mFormatter==null){var now=new Date();var dt=now.toLocaleString();msg="["+dt.substr(dt.indexOf(", ")+2)+":"+now.getMilliseconds()+"]["+level+"]["+message+"]\n"+stacktrace;}else{msg=this.mFormatter.format(level,message,stacktrace);}
this.mConsole.logStringMessage(msg);},flush:function(){return;},shutdown:function(){return;},classID:Components.ID("{89EFB683-B43B-40d9-B54B-AC8DCBCE4067}"),contractID:"@yahoo.com/ylogconsoleappender;1",QueryInterface:XPCOMUtils.generateQI([Components.interfaces.nsIYLogAppender])};function YLogger(){try{this.appenders=[];this.init(YahooExtConfig.mName);this.setLoggingLevel(this.YMLog_All);var pref=CC["@mozilla.org/preferences-service;1"].getService(CI.nsIPrefBranch);try{if(pref.getBoolPref("yahoo.ytff.debug.file")===true){var fileAppender=CC["@yahoo.com/ylogfileappender;1"].createInstance(CI.nsIYLogAppender);fileAppender.setFormatter(CC["@yahoo.com/ylogcsvformatter;1"].createInstance(CI.nsIYLogFormatter));this.registerLogAppender(fileAppender);}}catch(e){}
var str="**** System Info ****";try{var proto=CC["@mozilla.org/network/protocol;1?name=http"].getService(CI.nsIHttpProtocolHandler);str+="\nUser Agent :"+proto["userAgent"]+"\nToolbar Version:";if(pref.getBoolPref("yahoo.ytff.debug.console")===true){var consoleAppender=CC["@yahoo.com/ylogconsoleappender;1"].createInstance(CI.nsIYLogAppender);this.registerLogAppender(consoleAppender);}}catch(e){}
this.diagnose(str);}catch(e){}}
YLogger.prototype={YMLog_All:0x0,YMLog_Debug:0x1,YMLog_Info:0x2,YMLog_Warn:0x3,YMLog_Error:0x4,YMLog_Fatal:0x5,YMLog_Diagnose:0x6,appenders:[],count:0,level:0,mEnableStackTrace:false,mName:"Logger",mTestudTrace:null,mfTestudTraceEvent:null,mfTestudRunning:null,init:function(name){this.mName=name;try{this.mTestudTrace=ctypes.open("C:\\Testudinator\\bin\\YBenchmark.dll");if(this.mTestudTrace!=null)
{this.mfTestudTraceEvent=this.mTestudTrace.declare("JS_TraceEvent",ctypes.winapi_abi,ctypes.int32_t,ctypes.jschar.ptr,ctypes.int32_t);this.mfTestudRunning=this.mTestudTrace.declare("JS_IsTraceRunning",ctypes.winapi_abi,ctypes.int32_t);}}catch(e){if(this.mTestudTrace){this.mTestudTrace.close();this.mTestudTrace=null;this.mfTestudTraceEvent=null;this.mfTestudRunning=null;}
debug("YahooTestudinator::load::"+e);}},startTrace:function(eventName){if(this.mfTestudTraceEvent){this.mfTestudTraceEvent(eventName,1);}},stopTrace:function(eventName){if(this.mfTestudTraceEvent){this.mfTestudTraceEvent(eventName,2);}},isTraceRunning:function(){if(this.mfTestudRunning){return(this.mfTestudRunning()!=0);}
return false;},registerLogAppender:function(appender){for(var idx=0;idx<this.appenders.length;idx++){if(this.appenders[idx].getName()==appender.getName()){return;}}
debug("Adding appender :"+appender.getName());this.appenders.push(appender);appender.init(this.mName);},getName:function(){return this.mName;},log:function(level,msg){if(this.isEnabledFor(level)){var stacktrace="";if(this.mEnableStackTrace){stacktrace=this.stackTrace();}
var strLevel=this.getLevelString(level);for(appender in this.appenders){try{this.appenders[appender].append(strLevel,msg,stacktrace);}catch(e){}}
this.count++;}
if((level>=this.YMLog_Warn)||this.count>5){this.flush();this.count=0;}},diagnose:function(msg){this.log(this.YMLog_Diagnose,msg);},debug:function(msg){this.log(this.YMLog_Debug,msg);},info:function(msg){this.log(this.YMLog_Info,msg);},warn:function(msg){this.log(this.YMLog_Warn,msg);},error:function(msg){this.log(this.YMLog_Error,msg);},fatal:function(msg){this.log(this.YMLog_Fatal,msg);},setLoggingLevel:function(level){this.level=level;},enableStackTrace:function(){this.mEnableStackTrace=true;},disableStackTrace:function(){this.mEnableStackTrace=false;},getLoggingLevel:function(){return this.level;},isDebugEnabled:function(){return this.isEnabledFor(this.YMLog_Debug);},isInfoEnabled:function(){return this.isEnabledFor(this.YMLog_Info);},isWarnEnabled:function(){return this.isEnabledFor(this.YMLog_Warn);},isErrorEnabled:function(){return this.isEnabledFor(this.YMLog_Error);},isFatalEnabled:function(){return this.isEnabledFor(this.YMLog_Fatal);},isEnabledFor:function(level){return this.level<=level;},flush:function(){for(appender in this.appenders){this.appenders[appender].flush();}},shutdown:function(){for(appender in this.appenders){this.appenders[appender].shutdown();}
if(this.mTestudTrace){this.mfTestudTraceEvent=null;this.mTestudTrace.close();}},getLevelString:function(level){var ret="";switch(level){case this.YMLog_Debug:ret="Debug";break;case this.YMLog_Info:ret="Info";break;case this.YMLog_Warn:ret="Warn";break;case this.YMLog_Error:ret="Error";break;case this.YMLog_Fatal:ret="Fatal";break;case this.YMLog_Diagnose:ret="Diagnose";break;}
return ret;},stackTrace:function(num){num=num||999;var trace="";var caller=Components.stack.caller;caller=caller.caller.caller;try{while(caller&&num>0){if(caller.filename){var fileName=caller.filename;if(fileName.indexOf("chrome")!=0){var posExt=fileName.indexOf("extensions");if(posExt==-1){posExt=0;}
fileName=fileName.substr(posExt)}
trace+="\n"+fileName+":"+caller.lineNumber;}
num--;caller=caller.caller;}}catch(e){}
return trace;},classID:Components.ID("{43E76C2E-603D-4bf4-99CC-BAB4C289E4B7}"),contractID:"@yahoo.com/ytoolbarlogger;1",QueryInterface:XPCOMUtils.generateQI([Components.interfaces.nsIRunnable,Components.interfaces.nsIYLogger])};function debug(message){var console=CC["@mozilla.org/consoleservice;1"].getService(CI.nsIConsoleService);var d=new Date();var time="Logger :"+d.getHours()+":"+d.getMinutes()+":"+d.getSeconds();console.logStringMessage(time+": "+message);}
if(XPCOMUtils.generateNSGetFactory){var NSGetFactory=XPCOMUtils.generateNSGetFactory([YLogger,YLogFormatter,LogCSVFormatter,YLogConsoleAppender]);}else{var NSGetModule=XPCOMUtils.generateNSGetModule([YLogger,YLogFormatter,LogCSVFormatter,YLogConsoleAppender]);}