
Components.utils.import("resource://gre/modules/XPCOMUtils.jsm");var yahooCI=Components.interfaces;var yahooCC=Components.classes;var CC=Components.classes;var CI=Components.interfaces;function debug(message){var console=CC["@mozilla.org/consoleservice;1"].getService(CI.nsIConsoleService);var d=new Date();var time="Logger :"+d.getHours()+":"+d.getMinutes()+":"+d.getSeconds();console.logStringMessage(time+": "+message);}
function YLogFileAppender(){}
YLogFileAppender.prototype={buffer:null,file:null,mName:"FileAppender",mFormatter:null,mModuleName:null,init:function(modulename){this.mModuleName=modulename;},setName:function(name){this.mName=name;},getName:function(){return this.mName;},setFormatter:function(formatter){this.mFormatter=formatter;},append:function(level,message,stacktrace){var msg="";if(this.mFormatter!=null){msg=this.mFormatter.format(level,message,stacktrace);}else{msg=level+":"+message+":"+stacktrace;}
if(this.buffer===null){this.buffer="";}
this.buffer+=msg;this.buffer+='\n';},flush:function(){if(this.buffer!==null){if(this.file===null){this.createLogFile();}
this.file.write(this.buffer,this.buffer.length);this.buffer="";}},shutdown:function(){if(this.buffer!==null){this.flush();}
if(this.file!==null){this.file.close();this.file=null;}},getLogFileName:function(isBackUp){var name=this.mModuleName;var d=new Date();var weekday=new Array(7);weekday[0]="sun";weekday[1]="mon";weekday[2]="tue";weekday[3]="wed";weekday[4]="thu";weekday[5]="fri";weekday[6]="sat";name=name+"."+weekday[d.getDay()];if(isBackUp){name=name+".bak";}
name=name+".log";return name;},createLogFile:function(){var componentFile=__LOCATION__;var componentDir=componentFile.parent;var extensionDir=componentDir.parent;var mFileIO=yahooCC["@yahoo.com/fileio;1"].getService(yahooCI.nsIYahooFileIO2);var logdir=mFileIO.getUserCacheDir();var logfile=logdir.clone().QueryInterface(yahooCI.nsILocalFile);logfile.appendRelativePath(this.getLogFileName(false));if(logfile.exists()&&logfile.fileSize>=102400){var logfile_backup=logdir.clone().QueryInterface(yahooCI.nsILocalFile);logfile_backup.appendRelativePath(this.getLogFileName(true));if(logfile_backup.exists()){logfile_backup.remove(false);}
logfile.moveTo(logdir,this.getLogFileName(true));logfile=logdir.clone().QueryInterface(yahooCI.nsILocalFile);logfile.appendRelativePath(this.getLogFileName(false));}
this.file=yahooCC["@mozilla.org/network/file-output-stream;1"].createInstance(yahooCI.nsIFileOutputStream);this.file.init(logfile,0x02|0x08|0x10,0666,0);},classID:Components.ID("{398BF324-4B95-4E04-851C-876468795AD4}"),contractID:"@yahoo.com/ylogfileappender;1",QueryInterface:XPCOMUtils.generateQI([Components.interfaces.nsIYLogAppender])};if(XPCOMUtils.generateNSGetFactory){var NSGetFactory=XPCOMUtils.generateNSGetFactory([YLogFileAppender]);}else{var NSGetModule=XPCOMUtils.generateNSGetModule([YLogFileAppender]);}